<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actual only' => 'Actual only',
    'All records' => 'Tutti i record',
    'Are you sure you want to restore defaults?' => 'Sei sicuro di voler ripristinare i predefiniti?',
    'Are you sure you want to restore this item?' => 'Sei sicuro di voler ripristinare questo elemento?',
    'Back' => 'Indietro',
    'Context \'{name}\' required.' => 'Contesto \'{name}\' richiesto.',
    'Context object not found: {id}' => 'Oggetto del contesto {id} non trovato',
    'Create' => 'Nuovo',
    'Delete' => 'Cancella',
    'Deleted' => 'Cancellato',
    'Do it now' => 'Farlo ora',
    'Import' => 'Importa',
    'Move bottom' => 'Sposta in fondo',
    'Move down' => 'Sposta in giù',
    'Move top' => 'Sposta in cima',
    'Move up' => 'Sposta in su',
    'Object not found: {id}' => 'Oggetto non trovato: {id}',
    'Restore' => 'Ripristina',
    'Restore Defaults' => 'Ripristina predefiniti',
    'Update' => 'Modifica',
    'View' => 'Visualizza',
];
